```{r}
require(deSolve)
require(ggplot2)
require(patchwork)
cols <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#66CC99")

### The aim of this code is to make a figure that illustrates
### the isolation-only strategy in terms of Hansen & Day
### in terms of the public health terminology that I defined
#### elimination, suppression, and circuit breaker.


##### Parameters
# max daily rate of community member isolation
u1max <- 1

# max daily rate of traveler isolation
u2max <- 1

# constraint on community member isolation
C1max <- 1500

# constraint on traveller isolation
C2max <- 1500

# transmission rate
beta<-.0002

# importation rate
theta <- 0.25

mu<-0.334
# relative transmissibility of travellers
c<-1

T<-70

# daily vaccination rate
rho<-0

# start time for community isolation
tstart1<-0

# in case we wanted to do two switches
toff1 <- 1000 # currently set to not turn-off

# start time for restrictions on travellers
tstart2 <- 0
toff2 <- 1000

# community isolation function
u1fun<-function(t){
  u1 = u1max
  if(t<tstart1){
  u1 = 0}
  if(t<(toff1+10) & t>toff1){
    u1 = 0
  }
  return(u1)
}

# travel restrictions function
u2fun<-function(t){
  u2 = u2max
  if(t < tstart2){
  u2 = 0}
  if( t > toff2 & t < (toff2+10)){
    u2 = 0
  }
  return(u2)
}

# This is designed to trigger termination of the simulation when I1>0.5
rootfun <- function(t, y, parameters){
  I1 = y[2]
  # However, with importations, it doesn't make sense to have this as
  # the endpoint of the simulation, so instead I just set Imin = 0 and have
  # the simulation end at T=100.
  y1 = 0.5 - I1 
  return(y1)
}


SI<-function(t, y, parameters){
  S = y[1]
  I1 = y[2]
  I2 = y[3]
  C1 = y[4]
  C2 = y[5]
  iso1 = y[6]
  iso2 = y[7]
  u1 = u1fun(t)
  u2 = u2fun(t)
  
  if(C1 > C1max){
    u1 = 0
  }
  if(C2 > C2max){
    u2 = 0
  }
  
  dS = - beta*S*(I1 + c*I2) - rho*S
  dI1 = beta*S*(I1 + c*I2) - mu*I1 - u1*I1
  dI2 = theta - 2*mu*I2 - u2*I2
  dC1 = u1*I1
  dC2 = u2*I2
  diso1 = u1*I1 - mu*iso1
  diso2 = u2*I2 - 2*mu*iso2
  return(list(c(dS,dI1,dI2,dC1,dC2,diso1,diso2)))
}

### ELIMINATION ##### SUPPRESSION 
out1 <- ode(y = c(S=5000,I1=10,I2=0,C1=0,C2=0,iso1=0,iso2=0), parms = NULL, times = seq(0,T,.05), func = SI, events = list(func = NULL, root = TRUE, terminalroot = 1), rootfun=rootfun)
out1<- data.frame(out1)

J1 = cumsum(beta*out1$S*(out1$I1+c*out1$I2)*diff(c(0,out1$time)))

J.elim <- J1

u_1 = rep(0,length(J1))
u_1[which(diff(c(out1$C1[1],out1$C1))*diff(c(0,out1$time))>0.001)] = max(c(out1$I1,out1$iso1))

u_1.2 = rep(0,length(J1))
u_1.2[which(diff(c(out1$C2[1],out1$C2))*diff(c(0,out1$time))>0.001)] = max(c(out1$I2,out1$iso2))

out.elim <- data.frame(out1, u_1 = u_1, u_1.2 = u_1.2, j = J1)

#plot community infections
g.elim1 = ggplot(out.elim, aes(x = time, y = I1)) + 
  geom_ribbon(aes(ymin = 0, ymax = u_1), fill = cols[7], alpha = 0.2)+
  geom_line(color = cols[7], size = 2)+ geom_line(aes(y=iso1))+
  geom_line(aes(y = 0.5), color = "blue", linetype = "dashed")+
  ggtitle("Elimination")+ylab("Community prevalence") + xlim(0,20)+theme_classic()
g.elim1

#plot travel cases
g.elim2 = ggplot(out.elim, aes(x = time, y = I2)) +
  geom_ribbon(aes(ymin = 0, ymax = u_1.2), fill = cols[7], alpha = 0.2)+
  geom_line(color = cols[7], size = 2)+
  geom_line(aes(y=iso2))+
  ggtitle("")+ylab("Traveller's prevalence") + xlim(0,T)+theme_classic()
g.elim2

# Create a data frame for bar chart
values <- c(out.elim$j[nrow(out.elim)],out.elim$C1[nrow(out.elim)], out.elim$C2[nrow(out.elim)])
labels <- c("Cumulative new cases", "Comm. Isolation Resources Used", "TR Resources used")

data <- data.frame(
  Label = labels,
  Value = values
)

# Step 2: Create the bar plot using ggplot2
p <- ggplot(data, aes(x = Label, y = Value, fill = Label)) +
  geom_bar(stat = "identity", width = 0.5) +
  geom_text(aes(label = round(Value,2)), vjust = -0.5, size = 5) + 
  labs(title = "", x = "Category", y = "Value") +
  ylim(c(0,5000)) + 
  theme_minimal() +
  theme(legend.position = "none") +
  scale_fill_manual(values = c("red", "blue", "green"))

# Print the plot
print(p)
```



```{r}
#(same parameters except a lower u1max)
u1max <- 1
u2max <- 1

C1max <- 100
C2max <- 100

theta <- 1

out <- ode(y = c(S=5000,I1=10,I2=0,C1=0,C2=0,iso1=0,iso2=0), parms = NULL, times = seq(0,T,.05), func = SI, events = list(func = NULL, root = TRUE, terminalroot = 1), rootfun=rootfun)
out <- data.frame(out)
out.supp<-data.frame(out)

J = cumsum(beta*out$S*(out$I1+c*out$I2)*diff(c(0,out$time)))
J.supp <- J

u = rep(0,length(J))
u[which(diff(c(out$C1[1],out$C1))*diff(c(0,out$time))>0.001)] = max(c(out$I1,out$iso1))

u.1 = rep(0,length(J))
u.1[which(diff(c(out$C2[1],out$C2))*diff(c(0,out$time))>0.001)] = max(c(out$I2,out$iso2))

out.supp <- data.frame(out,u=u, u.1 = u.1, j =J )

#plot community cases
g.supp = ggplot(out.supp, aes(x = time, y = I1)) +
  geom_ribbon(aes(ymin = 0, ymax = u), fill = cols[2], alpha = 0.2)+
  geom_line(color = cols[2], size = 2)+
  geom_line(aes(y = 0.5), color = "blue", linetype = "dashed")+
  geom_line(aes(y=iso1))+ggtitle("Suppression")+ylab("") + xlim(0,T)+theme_classic()
g.supp

#plot magnified section
g.supp.1 = ggplot(out.supp, aes(x = time, y = I1)) +
  geom_ribbon(aes(ymin = 0, ymax = u), fill = cols[2], alpha = 0.2)+
  geom_line(color = cols[2], size = 2)+
  geom_line(aes(y = 0.5), color = "blue", linetype = "dashed")+
  geom_line(aes(y=iso1))+ggtitle("Magnified Plot")+ylab("") + xlim(0,50) + ylim(0,20) + theme_classic()
g.supp.1


#plot travel cases
g.supp1 = ggplot(out.supp, aes(x = time, y = I2)) +
  geom_ribbon(aes(ymin = 0, ymax = u.1), fill = cols[7], alpha = 0.2)+
  geom_line(color = cols[7], size = 2)+
  geom_line(aes(y=iso2))+
  ggtitle("")+ylab("Traveller's prevalence") + xlim(0,T)+theme_classic()
g.supp1

# Create a data frame for bar chart
values <- c(out.supp$j[nrow(out.supp)],out.supp$C1[nrow(out.supp)], out.supp$C2[nrow(out.supp)])
labels <- c("Cumulative new cases", "Comm. Isolation Resources Used", "TR Resources used")

data <- data.frame(
  Label = labels,
  Value = values
)

# Step 2: Create the bar plot using ggplot2
p <- ggplot(data, aes(x = Label, y = Value, fill = Label)) +
  geom_bar(stat = "identity", width = 0.5) +
  geom_text(aes(label = round(Value,2)), vjust = -0.5, size = 5) + 
  labs(title = "", x = "Category", y = "Value") +
  ylim(c(0,5000)) + 
  theme_minimal() +
  theme(legend.position = "none") +
  scale_fill_manual(values = c("red", "blue", "green"))

# Print the plot
print(p)
```
```{r}

fig1 = g.supp + g.supp.1
plot_annotation(tag_levels = 'A')
fig1

```



```{r}
###### CIRCUIT BREAKER (a lower value of the constraint)
### (also times of on and off to illustrate that timing doesn't matter)

C1max <- 400
C2max <- 400

toff1<-11
toff2 <- 11

out2 <- ode(y = c(S=5000,I1=10,I2=0,C1=0,C2=0,iso1=0,iso2=0), parms = NULL, times = seq(0,T,.05), func = SI, events = list(func = NULL, root = TRUE, terminalroot = 1), rootfun=rootfun)
out2 <- data.frame(out2)
out.circ<-out2

J2 = cumsum(beta*out2$S*(out2$I1+c*out2$I2)*diff(c(0,out2$time)))

u_2 = rep(0,length(J2))
u_2[which(diff(c(out2$C1[1],out2$C1))*diff(c(0,out2$time))>0.001)] = max(c(out2$I1,out2$iso1))

u_2.2 = rep(0,length(J2))
u_2.2[which(diff(c(out2$C2[1],out2$C2))*diff(c(0,out2$time))>0.001)] = max(c(out2$I2,out2$iso2))

out.circ <- data.frame(out2, u_2 = u_2, u_2.2 = u_2.2, j = J2)

#plot community infections
g.circ1 = ggplot(out.circ, aes(x = time, y = I1)) + 
  geom_ribbon(aes(ymin = 0, ymax = u_2), fill = cols[7], alpha = 0.2)+
  geom_line(color = cols[7], size = 2)+ geom_line(aes(y=iso1))+
  ggtitle("Circuit Breaker 1")+ylab("Community prevalence") + xlim(0,T)+theme_classic()
g.circ1

#plot travel cases
g.circ1.2 = ggplot(out.circ, aes(x = time, y = I2)) +
  geom_ribbon(aes(ymin = 0, ymax = u_2.2), fill = cols[7], alpha = 0.2)+
  geom_line(color = cols[7], size = 2)+
  geom_line(aes(y=iso2))+
  ggtitle("")+ylab("Traveller's prevalence") + xlim(0,T)+theme_classic()
g.circ1.2

# Create a data frame for bar chart
values <- c(out.circ$j[nrow(out.circ)],out.circ$C1[nrow(out.circ)], out.circ$C2[nrow(out.circ)])
labels <- c("Cumulative new cases", "Comm. Isolation Resources Used", "TR Resources used")

data <- data.frame(
  Label = labels,
  Value = values
)

# Step 2: Create the bar plot using ggplot2
p <- ggplot(data, aes(x = Label, y = Value, fill = Label)) +
  geom_bar(stat = "identity", width = 0.5) +
  geom_text(aes(label = round(Value,2)), vjust = -0.5, size = 5) + 
  labs(title = "", x = "Category", y = "Value") +
  ylim(c(0,5000)) + 
  theme_minimal() +
  theme(legend.position = "none") +
  scale_fill_manual(values = c("red", "blue", "green"))

# Print the plot
print(p)
```





```{r}
#### A different circuit-breaker with the same parameters as above
tstart1 <- 5
tstart2 <- 5

toff1<-15
toff1<-15

out3 <- ode(y = c(S=5000,I1=10,I2=0,C1=0,C2=0,iso1=0, iso2=0), parms = NULL, times = seq(0,T,.05), func = SI, events = list(func = NULL, root = TRUE, terminalroot = 1), rootfun=rootfun)
out3 <- data.frame(out3)

out.circ2<-out3


J3 = cumsum(beta*out3$S*(out3$I1+c*out3$I2)*diff(c(0,out3$time)))

u_3 = rep(0,length(J3))
u_3[which(diff(c(out3$C1[1],out3$C1))*diff(c(0,out3$time))>0.001)] = max(c(out3$I1,out3$iso1))

u_3.2 = rep(0,length(J3))
u_3.2[which(diff(c(out3$C2[1],out3$C2))*diff(c(0,out3$time))>0.001)] = max(c(out3$I2,out3$iso2))

out.circ2 <- data.frame(out3, u_3 = u_3, u_3.2 = u_3.2, j = J3)

#plot community infections
g.circ2 = ggplot(out.circ2, aes(x = time, y = I1)) + 
  geom_ribbon(aes(ymin = 0, ymax = u_3), fill = cols[7], alpha = 0.2)+
  geom_line(color = cols[7], size = 2)+ geom_line(aes(y=iso1))+
  ggtitle("Circuit breaker 2")+ylab("Community prevalence") + xlim(0,T)+theme_classic()
g.circ2

#plot travel cases
g.circ2.2 = ggplot(out.circ2, aes(x = time, y = I2)) +
  geom_ribbon(aes(ymin = 0, ymax = u_3.2), fill = cols[7], alpha = 0.2)+
  geom_line(color = cols[7], size = 2)+
  geom_line(aes(y=iso2))+
  ggtitle("")+ylab("Traveller's prevalence") + xlim(0,T)+theme_classic()
g.circ2.2



# Create a data frame for bar chart
values <- c(out.circ2$j[nrow(out.circ2)],out.circ2$C1[nrow(out.circ2)], out.circ2$C2[nrow(out.circ2)])
labels <- c("Cumulative new cases", "Comm. Isolation Resources Used", "TR Resources used")

data <- data.frame(
  Label = labels,
  Value = values
)

# Step 2: Create the bar plot using ggplot2
p <- ggplot(data, aes(x = Label, y = Value, fill = Label)) +
  geom_bar(stat = "identity", width = 0.5) +
  geom_text(aes(label = round(Value,2)), vjust = -0.5, size = 5) + 
  labs(title = "", x = "Category", y = "Value") +
  ylim(c(0,5000)) + 
  theme_minimal() +
  theme(legend.position = "none") +
  scale_fill_manual(values = c("red", "blue", "green"))

# Print the plot
print(p)

fig2 = g.circ1+g.circ1.2+ g.circ2 + g.circ2.2
fig2



```



```{r}
J.circ = ggplot()+
  geom_ribbon(data=out.circ,aes(x=time,ymin = 0, ymax = u_2.2*(max(J2)/max(I2))), fill = cols[4], alpha = 0.2)+
  geom_ribbon(data=out.circ2,aes(x=time,ymin = 0, ymax = u_3.2*(max(J3)/max(I2))), fill = cols[6], alpha = 0.2)+
  geom_line(data=out.circ, aes(x = time, y = J2),color = cols[4], size = 2)+
  geom_line(data=out.circ2, aes(x = time, y = J3),color = cols[6], size = 2)+ylab("Cumulative cases")+ggtitle("Circuit breaker 1 & 2 equivalence")+theme_classic()

g1=g.elim1
g2=fig1 
g3 = fig2
g4 = g.circ2+g.circ2.2
fig = g1/g2+g3/g4/J.circ+
  plot_annotation(tag_levels = 'A')-> r
r
ggsave("~/Desktop/Amy R codes/mixed_policy.png", width = 18, height = 40, units = "cm")
```
