---
title: "R Notebook"
output: html_notebook
---

```{r}
require(deSolve)
require(ggplot2)
require(patchwork)
library(cowplot)

cols <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#66CC99")

### The aim of this code is to make a figure that illustrates
### the Travel restrictions-only strategy
### in terms of the public health terminology that I defined
#### elimination, suppression, and circuit breaker.


##### Parameters
# max daily rate of traveler isolation
u2max <- 0

# constraint on traveller isolation
C2max <- 500

# transmission rate
beta<- 0.0002

# importation rate
theta <- 5

mu <- 0.334
# relative transmissibility of travellers
c <- 1

T <- 70
# daily vaccination rate
rho <- 0


# in case we wanted to do two switches
toff2 <- 1000 # currently set to not turn-off
# start time for restrictions on travellers
tstart2 <- 0


# travel restrictions function
u2fun<-function(t){
  u2 = u2max
  if(t < tstart2){
  u2 = 0}
  if( t > toff2 & t < (toff2+10)){
    u2 = 0
  }
  return(u2)
}


# travel restrictions function
#u2fun <- function(t){
  #if(t > tstart2){
   # u2 = u2max}
  #else{
   # u2 = 0
 # }
 # return(u2)
#}

# This is designed to trigger termination of the simulation when I1 < 0.5
rootfun <- function(t, y, parameters){
  I1 = y[2]
  # However, with importations, it doesn't make sense to have this as
  # the endpoint of the simulation, so instead I just set Imin = 0 and have
  # the simulation end at T=100.
  y1 = 0.5 - I1 
  return(y1)
}


SI<-function(t, y, parameters){
  S = y[1]
  I1 = y[2]
  I2 = y[3]
  C2 = y[4]
  iso = y[5]
  u2 = u2fun(t)
  

  if(C2 > C2max){
    u2 = 0
  }
  
  dS = - beta*S*(I1 + c*I2) - rho*S
  dI1 = beta*S*(I1 + c*I2) - mu*I1
  dI2 = theta - 2*mu*I2 - u2*I2
  dC2 = u2*I2
  diso = u2*I2 - 2*mu*iso
  return(list(c(dS,dI1,dI2,dC2,diso)))
}

### ELIMINATION/SUPPRESSION (Without travel measures)
out1 <- ode(y = c(S = 5000, I1 = 11, I2 = 0, C2 = 0, iso = 0), parms = NULL, times = seq(0,T,.05), func = SI, events = list(func = NULL, root = TRUE, terminalroot = 1), rootfun=rootfun)
out1<- data.frame(out1)
J1 = cumsum(beta*out1$S*(out1$I1+c*out1$I2)*diff(c(0,out1$time)))
J.elim <- J1

u = rep(0,length(J1))

u[which(diff(c(out1$C2[1],out1$C2))*diff(c(0,out1$time)) > 0.001)] = max(c(out1$I2,out1$iso))

out.elim <- data.frame(out1,u=u, j = J1)


#plot community infections
g.elim1 = ggplot(out.elim, aes(x = time, y = I1)) + 
  geom_line(color = cols[7], size = 1)+
  geom_line(aes(y = 0.5), color = "blue", linetype = "dashed")+
  ggtitle("Without Travel measures")+ylab("Community prevalence") + xlim(0,T)+ theme_classic()
g.elim1

#Magnified Plot
g.elim1.1 = ggplot(out.elim, aes(x = time, y = I1)) + 
  geom_line(color = cols[7], size = 1)+
  geom_line(aes(y = 0.5), color = "blue", linetype = "dashed")+
  ggtitle("Magnified Plot")+ylab("Community prevalence") + xlim(0,T)+ ylim(0,10) + theme_classic()
g.elim1.1

fig = g.elim1+ g.elim1.1+
  plot_annotation(tag_levels = 'A')
fig



#plot travel cases
g.elim2 = ggplot(out.elim, aes(x = time, y = I2)) +
  geom_ribbon(aes(ymin = 0, ymax = u), fill = cols[7], alpha = 0.2)+
  geom_line(color = cols[7], size = 2)+
  geom_line(aes(y=iso))+
  ggtitle(" ")+ylab("Traveller's prevalence") + xlim(0,T)+theme_classic()
g.elim2



# Create a data frame for bar chart
values <- c(out.elim$j[nrow(out.elim)], out.elim$C2[nrow(out.elim)])
labels <- c("Cumulative new cases", "Resources Used")

data <- data.frame(
  Label = labels,
  Value = values
)

# Step 2: Create the bar plot using ggplot2
p <- ggplot(data, aes(x = Label, y = Value, fill = Label)) +
  geom_bar(stat = "identity", width = 0.5) +
  geom_text(aes(label = round(Value,2)), vjust = -0.5, size = 5) + 
  labs(title = "Values of J and C", x = "Category", y = "Value") +
  ylim(c(0,5000)) + 
  theme_minimal() +
  theme(legend.position = "none") +
  scale_fill_manual(values = c("red", "green"))

# Print the plot
print(p)

```




```{r}
##### ELIMINATION/SUPPRESSION (With travel measures u2max)
u2max <- 2 
T = 70
C2max <- 500

out2 <- ode(y = c(S = 5000, I1 = 11, I2 = 0,  C2 = 0, iso = 0), parms = NULL, times = seq(0,T,.05), func = SI, events = list(func = NULL, root = TRUE, terminalroot = 1), rootfun=rootfun)
out2 <- data.frame(out2)

out.supp<-data.frame(out2)

J2 = cumsum(beta*out2$S*(out2$I1+c*out2$I2)*diff(c(0,out2$time)))
J.supp <- J2

u_1 = rep(0,length(J2))
u_1[which(diff(c(out2$C2[1],out2$C2))*diff(c(0,out2$time))>0.001)] = max(c(out2$I2,out2$iso))

out.supp <- data.frame(out2,u_1=u_1, j = J2)

#plot community infections
g.supp1 = ggplot(out.supp, aes(x = time, y = I1)) + 
  geom_line(color = cols[7], size = 1)+
  geom_line(aes(y = 0.5), color = "blue", linetype = "dashed")+
  ggtitle(" With Travel measures")+ylab("Community prevalence") + xlim(0,T)+theme_classic()
g.supp1

#Magnified plot
g.supp1.1 = ggplot(out.supp, aes(x = time, y = I1)) + 
  geom_line(color = cols[7], size = 1)+
  geom_line(aes(y = 0.5), color = "blue", linetype = "dashed")+
  ggtitle(" Magnified Plot")+ylab("Community prevalence") + xlim(0,T)+ylim(0,10)+theme_classic()

#plot travel cases
g.supp2 = ggplot(out.supp, aes(x = time, y = I2)) +
  geom_ribbon(aes(ymin = 0, ymax = u_1), fill = cols[2], alpha = 0.2)+
  geom_line(color = cols[2], size = 2)+
  geom_line(aes(y=iso))+ggtitle(" ")+ylab("Traveller's prevalence") + xlim(0,T)+theme_classic()
g.supp2

fig2 = g.supp1+ g.supp1.1+
  plot_annotation(tag_levels = 'A')
fig2

# Create a data frame for bar chart
values <- c(out.supp$j[nrow(out.supp)], out.supp$C2[nrow(out.supp)])
labels <- c("Cumulative new cases", "Resources Used")

data <- data.frame(
  Label = labels,
  Value = values
)

# Step 2: Create the bar plot using ggplot2
p <- ggplot(data, aes(x = Label, y = Value, fill = Label)) +
  geom_bar(stat = "identity", width = 0.5) +
  geom_text(aes(label = round(Value,2)), vjust = -0.5, size = 5) + 
  labs(title = "Values of J and C", x = "Category", y = "Value") +
  ylim(c(0,5000)) + 
  theme_minimal() +
  theme(legend.position = "none") +
  scale_fill_manual(values = c("red", "green"))

# Print the plot
print(p)
```


```{r}

fig = g.elim1+ g.elim1.1+g.supp1+ g.supp1.1
  plot_annotation(tag_levels = 'A')
fig


```




```{r}
###### CIRCUIT BREAKER (a lower value of the constraint)
### (also times of on and off to illustrate that timing doesn't matter)
C2max <- 400
T = 70
toff2<-10
out3 <- ode(y = c(S=5000, I1=11, I2=0, C2=0, iso=0), parms = NULL, times = seq(0,T,.05), func = SI, events = list(func = NULL, root = TRUE, terminalroot = 1), rootfun=rootfun)

out3 <- data.frame(out3)
out.circ<-out3

J3 = cumsum(beta*out3$S*(out3$I1+c*out3$I2)*diff(c(0,out3$time)))
u_2 = rep(0,length(J3))
u_2[which(diff(c(out3$C2[1],out3$C2))*diff(c(0,out3$time))>0.001)] = max(c(out3$I2,out3$iso))

out.circ <- data.frame(out3, u_2=u_2, j=J3)

#plot community infections
g.circ1 = ggplot(out.circ, aes(x = time, y = I1)) + 
  geom_line(color = cols[7], size = 2)+
  ggtitle("")+ylab("Community prevalence") + xlim(0,T)+theme_classic()
g.circ1

#plot travel cases
g.circ1.2 = ggplot(out.circ, aes(x = time, y = I2)) +
  geom_ribbon(aes(ymin = 0, ymax = u_2), fill = cols[4], alpha = 0.2)+
  geom_line(color = cols[4], size = 2)+geom_line(aes(y=iso))+ggtitle("Circuit breaker 1")+ylab("Traveller's prevalence") + xlim(0,T) + theme_classic()
g.circ1.2

# Create a data frame for ggplot (Bar plots)
values <- c(out.circ$j[nrow(out.circ)], out.circ$C2[nrow(out.circ)])
labels <- c("Cummulative new cases", "Resources used")

data <- data.frame(
  Label = labels,
  Value = values
)

# Step 2: Create the bar plot using ggplot2
p <- ggplot(data, aes(x = Label, y = Value, fill = Label)) +
  geom_bar(stat = "identity", width = 0.5) +
  geom_text(aes(label = round(Value,2)), vjust = -0.5, size = 5) + 
  labs(title = "Values of J and C", x = "Category", y = "Value") +
  ylim(c(0,5000)) + 
  theme_minimal() +
  theme(legend.position = "none") +
  scale_fill_manual(values = c("red", "green"))

# Print the plot
print(p)

```






```{r}
#### A different circuit-breaker with the same parameters as above
tstart2<-5
toff2<-1000
out4 <- ode(y = c(S=5000,I1=10,I2=0,C2=0,iso=0), parms = NULL, times = seq(0,T,.05), func = SI, events = list(func = NULL, root = TRUE, terminalroot = 1), rootfun=rootfun)
out4 <- data.frame(out4)
out.circ2<-out4

J4 = cumsum(beta*out4$S*(out4$I1+c*out4$I2)*diff(c(0,out4$time)))

u_3 = rep(0,length(J4))

u_3[which(diff(c(out4$C2[1],out4$C2))*diff(c(0,out4$time))>0.001)] = max(c(out4$I2,out4$iso))

out.circ2 <- data.frame(out4, u_3 = u_3, j = J4)


#plot community infections
g.circ2 = ggplot(out.circ2, aes(x = time, y = I1)) + 
  geom_line(color = cols[7], size = 2)+
  ggtitle("")+ylab("Community prevalence") + xlim(0,T)+theme_classic()
g.circ2

#plot travel cases
g.circ2.1 = ggplot(out.circ2, aes(x = time, y = I2)) +
  geom_ribbon(aes(ymin = 0, ymax = u_3), fill = cols[6], alpha = 0.2)+
  geom_line(color = cols[6], size = 2)+
  geom_line(aes(y=iso))+
  ggtitle("Circuit breaker 2")+ylab("") + xlim(0,T) + theme_classic()
g.circ2.1


# Create a data frame for ggplot (Bar plots)
values <- c(out.circ2$j[nrow(out.circ2)], out.circ2$C2[nrow(out.circ2)])
labels <- c("Cummulative new cases", "Resources used")

data <- data.frame(
  Label = labels,
  Value = values
)

# Step 2: Create the bar plot using ggplot2
p <- ggplot(data, aes(x = Label, y = Value, fill = Label)) +
  geom_bar(stat = "identity", width = 0.5) +
  geom_text(aes(label = round(Value,2)), vjust = -0.5, size = 5) + 
  labs(title = "Values of J and C", x = "Category", y = "Value") +
  ylim(c(0,5000)) + 
  theme_minimal() +
  theme(legend.position = "none") +
  scale_fill_manual(values = c("red", "green"))

# Print the plot
print(p)
```



```{r fig.width=12, fig.height=7}
J.circ = ggplot()+
  geom_ribbon(data=out.circ,aes(x=time,ymin = 0, ymax = u_2*(max(J3)/max(I2))), fill = cols[4], alpha = 0.2)+
  geom_ribbon(data=out.circ2,aes(x=time,ymin = 0, ymax = u_3*(max(J4)/max(I2))), fill = cols[6], alpha = 0.2)+
  geom_line(data=out.circ, aes(x = time, y = J3),color = cols[4], size = 2)+
  geom_line(data=out.circ2, aes(x = time, y = J4),color = cols[6], size = 2)+ylab("Cumulative cases")+ggtitle("Circuit breaker 1 & 2 equivalence")+theme_classic()

g1=g.elim2+g.supp2
g2=g.circ1.2+g.circ2.1
fig = g1/g2/J.circ+
  plot_annotation(tag_levels = 'A') -> r
r
 ggsave("~/Desktop/Amy R codes/TR_only.png", width = 20, height = 15, units = "cm")

```




